# Numpy

In [114]:
import numpy as np

In [115]:
myarr= np.array([1,2,3,4,5]) # creating numpy array

In [116]:
myarr

array([1, 2, 3, 4, 5])

In [117]:
myarr= np.array([1,2,3,4,5], np.int32)  # memory management

In [118]:
myarr

array([1, 2, 3, 4, 5])

In [119]:
myarr.dtype

dtype('int32')

In [120]:
myarr.shape # shape of array

(5,)

In [121]:
larr= np.array([[1,2,3],[4,5,6],[7,8,9]])  # 2D numpy array

In [122]:
larr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
larr.dtype

dtype('int32')

In [124]:
larr.shape

(3, 3)

In [125]:
larr.size

9

In [126]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [127]:
zeros= np.zeros((3,4))  # make all zero with give shape

In [128]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [129]:
zeros.shape

(3, 4)

In [130]:
zeros.dtype

dtype('float64')

In [131]:
rng= np.arange(15) # make an array with the given range

In [132]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [133]:
lspace = np.linspace(1,5,12)   # 1 to 5 equally linearly spaced 12 elements

In [134]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [135]:
np.empty((4,3))  # will give an array of given shape with random elements

array([[1.        , 1.36363636, 1.72727273],
       [2.09090909, 2.45454545, 2.81818182],
       [3.18181818, 3.54545455, 3.90909091],
       [4.27272727, 4.63636364, 5.        ]])

In [136]:
a=np.array([[1,2,3,4],[5,6,7,8]])
em_like=np.empty_like(a)  # it will copy the shape of an array and provide empty array

In [137]:
em_like

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [138]:
# identity matrix
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [139]:
arr= np.arange(99)

In [140]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [141]:
arr.reshape(3,33)  # it will reshape the array [3][33]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [142]:
arr.ravel()  # make 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [143]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [144]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
ar.sum(axis=0)  # sum of x axis

array([12, 15, 18])

In [146]:
ar.sum(axis=1)  # sum of y axis

array([ 6, 15, 24])

In [147]:
ar.T  # Transpose matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [148]:
ar.flat  # flat the array

In [149]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [150]:
ar.ndim  # no of dimension

2

In [151]:
ar.nbytes  # total bytes consumed

36

In [152]:
one= np.array([4,2,1,6,7])

In [153]:
one

array([4, 2, 1, 6, 7])

In [154]:
one.argmax()  # index of maximum element


4

In [155]:
one.argmin()  # index of minimum element

2

In [156]:
one.argsort()  # sort of indexes on the basis of array element

array([2, 1, 0, 3, 4], dtype=int64)

In [157]:
two=np.array([[1,2,3],[3,4,2],[7,4,2]])

In [158]:
two

array([[1, 2, 3],
       [3, 4, 2],
       [7, 4, 2]])

In [159]:
two.argmin()

0

In [160]:
two.argmax()  # first flat then calculate 

6

In [161]:
two.argmin(axis=0)  # x axis min index

array([0, 0, 1], dtype=int64)

In [162]:
two.argmin(axis=1)  # y axis min index

array([0, 2, 2], dtype=int64)

In [163]:
two.argsort()

array([[0, 1, 2],
       [2, 0, 1],
       [2, 1, 0]], dtype=int64)

In [164]:
two.argsort(axis=0)

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 0]], dtype=int64)

In [165]:
two.argsort(axis=1)

array([[0, 1, 2],
       [2, 0, 1],
       [2, 1, 0]], dtype=int64)

In [166]:
two.ravel()

array([1, 2, 3, 3, 4, 2, 7, 4, 2])

In [167]:
two.reshape(9,1)

array([[1],
       [2],
       [3],
       [3],
       [4],
       [2],
       [7],
       [4],
       [2]])

In [168]:
# Math
arr1= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [169]:
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [172]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [173]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [174]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [175]:
arr1.sum()  # all sum

45

In [176]:
arr1.min()

1

In [177]:
arr1.max()

9

In [178]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [179]:
# Search
np.where(arr1==5)

(array([1], dtype=int64), array([1], dtype=int64))

In [180]:
np.where(arr1>6)  # [2,0],[2,1],[2,2]

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [181]:
type(np.where(arr1>6))

tuple

In [182]:
np.count_nonzero(arr1)

9

In [183]:
# Numpy gives efficient storage
import sys

In [184]:
py_ar=[1,2,3,4]

In [185]:
np_ar=np.array([1,2,3,4])

In [186]:
sys.getsizeof(1)*len(py_ar)

112

In [187]:
np_ar.itemsize*np_ar.size

16